implementation tests
dawba/market-place pull request #36
Opened 2024-06-06 10:47 UTC by Konrad1w

I encountered an issue while implementing tests for services, particularly within the AdvertisementManagementServiceTest class, specifically with the testDeleteAdvertisement method. I struggled with verifying whether an email was sent to the observers. Consequently, I decided to switch gears and begin implementing tests for controllers. However, before diving into that, I wanted to ensure that the existing tests in the CategoryManagementControllerTest class were functioning correctly. Unfortunately, when I attempted to run them, I encountered an error which I previously mentioned to you, @dimmonn.

2024-06-07 11:05 UTC, dawba commented
@Konrad1w could you provide some example of the error you've encountered?
I have checked out the build logs and its 68 PASS / 17 FAIL, which is a nice result. 

I will take a look at the tests you've implemented and see if there is something more to add. 
For now, the coverage looks great given only a few entities to test.

2024-06-07 19:34 UTC, dimmonn commented on src/test/java/org/marketplace/controllers/UserManagementControllerTest.java
> +    void getAllUsers() {
this and below are yet to be done

2024-06-07 19:35 UTC, dimmonn commented on src/test/java/org/marketplace/services/AdvertisementImageManagementServiceTest.java
> +        given(advertisementImageManagementRepository.findById(advertisementImage.getId())).willReturn(Optional.empty());
i would add real workflow here, there is no need to mock it up, we can just add stuff to h2 before each test
normally we want to use mocks as an exceptional situation

2024-06-07 19:39 UTC, dimmonn reviewed
we can keep current version just to save time 👍
in a real life project i would use mocks as an exceptional situation when things are really out of our control and therefore we want to mock up, in 99% of cases we can test based on abstractions/interfaces etc

2024-06-07 20:00 UTC, Konrad1w commented
I added tests for the user and category controllers. Wen trying to add tests for the advertisement controller, I encountered an error related to Java 8 LocalDateTime. According to the compiler's suggestion, I added com.fasterxml.jackson.datatype, but it didn't help, so I reverted that solution.

2024-06-08 06:52 UTC, Konrad1w commented
> I added tests for the user and category controllers. Wen trying to add tests for the advertisement controller, I encountered an error related to Java 8 LocalDateTime. According to the compiler's suggestion, I added com.fasterxml.jackson.datatype, but it didn't help, so I reverted that solution. Can somebody look at it?

Ok I solved this problem. I was connected with version Jackson, which I added. Here is solution 
![image](https://github.com/dawba/market-place/assets/130360173/79711999-b67b-431b-9c7c-046b0278e80f)

2024-06-09 21:00 UTC, dawba requested changes
Great job! 

I like how the refreshed version looks like and feel like we test most of what is needed.

Please take a look at requested changes - and when finished I will get to creating a testing raport for our app.

2024-06-09 21:00 UTC, dawba commented on src/main/java/org/marketplace/services/AdvertisementManagementService.java
> +        if (advertisementId == null) {
We dont have to include an "if-else" block here.
The if clause is sufficient - just do a try-catch blok after the if statement, as when IF is not satisfied, we will execute the rest of the code.

2024-06-09 21:00 UTC, dawba commented on src/main/java/org/marketplace/models/Advertisement.java
> +    private Long owner;
I am not seeing any usage of it, is it really needed? 
We have the owner based on the `Advertisement.user.id` field

2024-06-09 21:00 UTC, dawba commented on src/test/java/org/marketplace/controllers/AdvertisementManagementControllerTest.java
> +    public void createAdvertisement() throws Exception {
Given the constraints on advertisement entity, I would test the border values for title/description fields, or passing the userId/categoryId as nullish.

2024-06-09 21:00 UTC, dawba commented on src/test/java/org/marketplace/controllers/AdvertisementManagementControllerTest.java
> +        //String payload = "{\"id\":1,\"title\":\"SampleAdvertisement\",\"description\":\"Thisisasampleadvertisement\",\"category\":{\"id\":1,\"name\":\"SampleCategory\"},\"user\":{\"id\":1,\"usernam
If not used, I would just delete it I guess.

2024-06-09 21:00 UTC, dawba commented on src/test/java/org/marketplace/controllers/UserManagementControllerTest.java
> +class UserManagementControllerTest {
also:
maybe test the flow of

`register -> confirm -> login` to check the isVerified field and user access.

2024-06-09 21:00 UTC, dawba commented on src/test/java/org/marketplace/services/AdvertisementImageManagementServiceTest.java
> +        given(advertisementImageManagementRepository.findById(advertisementImage.getId())).willReturn(Optional.empty());
Looking at the advertisement image this is a part of the project we failed at and have not fully implemented it, which is a bit of a pity.

Will be included as something we can learn from, in conclusions of this project.

2024-06-09 21:00 UTC, dawba commented on src/test/java/org/marketplace/controllers/UserManagementControllerTest.java
> +class UserManagementControllerTest {
Also, the constraints on phone/login length would be nice to be tested

2024-06-09 21:00 UTC, dawba commented on src/test/java/org/marketplace/services/CategoryManagementServiceTest.java
> +    public void testAddCategoryWithNullName() {
given that we test the constraints here - why not test the border values of the category?
so drop in the 
names of length 1, 2, 20 and 21 + null
so we get it done in one test.

2024-06-09 21:00 UTC, dawba commented on src/test/java/org/marketplace/services/CategoryManagementServiceTest.java
> +    public void testAddCategoryWithShortName() {
I know that we test it here, but maybe just do it in one single test, and then we can test other methods from the service?

2024-06-09 21:00 UTC, dawba commented on src/test/java/org/marketplace/util/TestUtil.java
> +public class TestUtil {
Couldnt we make it more reusable with passed generic type?
and do a switchcase here if you need a different logic for advertisement id.

Otherwise we duplicate our code a little bit too much.

so I would see something like

```java
    public static <T> Long extractIdFromMvcResult(MvcResult result, TypeReference<Response<T>> typeReference) {
        try {
            String responseBody = result.getResponse().getContentAsString();
            Response<T> response = mapper.readValue(responseBody, typeReference);
            return response.getData().getId();
        } catch (Exception e) {
            throw new RuntimeException("Failed to extract ID from MvcResult", e);
        }
    }

    public static Long extractAdvertisementIdFromMvcResult(MvcResult result) {
        return extractIdFromMvcResult(result, new TypeReference<Response<Advertisement>>() {});
    }

    public static Long extractUserIdFromMvcResult(MvcResult result) {
        return extractIdFromMvcResult(result, new TypeReference<Response<User>>() {});
    }

    public static Long extractCategoryIdFromMvcResult(MvcResult result) {
        return extractIdFromMvcResult(result, new TypeReference<Response<Category>>() {});
    }

    public static Long extractAdvertisementImageIdFromMvcResult(MvcResult result) {
        return extractIdFromMvcResult(result, new TypeReference<Response<AdvertisementImage>>() {});
    }
    ```
    
    or maybe it is possible to just make it generic and just call `extractIdFromMvcResult`

2024-06-09 21:13 UTC, Konrad1w commented on src/main/java/org/marketplace/models/Advertisement.java
> +    private Long owner;
I had to add it, because I got error running 'TestUtil.extractAdvertisementIdFromMvcResult' method. Error was connected with mapping Advertisement.

2024-06-09 21:18 UTC, Konrad1w commented on src/test/java/org/marketplace/util/TestUtil.java
> +public class TestUtil {
It looks like nice, I will add it.

2024-06-13 17:36 UTC, merged